# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
#workflows:
  #docker-react-wf: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.

workflows:
  my-workflow:
    jobs:
      - run-tests:
          context:
            - org-global
            - my-docker-context
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: |
        echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - run: docker build -t prasagr/docker-react -f Dockerfile.dev .
      - run: docker run -e CI=true prasagr/docker-react npm run test
     # - run:
     #   name: Docker run image and perform npm run test
     #   command: |
     #     docker run -e CI=true prasagra/docker-react npm run test