# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs: 
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
#workflows:
  #docker-react-wf: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.

workflows:
  docker-react-wf:
    jobs:
      - build:
          context:
            - org-global
            - my-docker-context
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Docker build image
          command: |
            echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
            docker build -t prasagr/docker-react -f Dockerfile.dev .
      - run: 
          name: Docker run npm test
          command: docker run -e CI=true prasagr/docker-react npm run test
     # - run:
     #   name: Docker run image and perform npm run test
     #   command: |
     #     docker run -e CI=true prasagra/docker-react npm run test